title: Saubhagya india
url: "https://saubhagyaindia.github.io/mobile-app"
baseurl: "https://saubhagyaindia.github.io/mobile-app"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE